excluded:
  - Pods
disabled_rules:
  - todo
  - force_cast
  - trailing_whitespace
opt_in_rules:
  - explicit_init
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
identifier_name:
  min_length: 1
line_length:
  warning: 190
  error: 250
function_body_length:
  warning: 70
  error: 100
type_body_length:
  warning: 250
  error: 300
file_length:
  warning: 600
  error: 1000
